/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const MoodLazyImport = createFileRoute('/mood')()
const JournalLazyImport = createFileRoute('/journal')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MoodLazyRoute = MoodLazyImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/mood.lazy').then((d) => d.Route))

const JournalLazyRoute = JournalLazyImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/journal.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalLazyImport
      parentRoute: typeof rootRoute
    }
    '/mood': {
      id: '/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof MoodLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/journal': typeof JournalLazyRoute
  '/mood': typeof MoodLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/journal': typeof JournalLazyRoute
  '/mood': typeof MoodLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/journal': typeof JournalLazyRoute
  '/mood': typeof MoodLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/journal' | '/mood'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/journal' | '/mood'
  id: '__root__' | '/' | '/journal' | '/mood'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  JournalLazyRoute: typeof JournalLazyRoute
  MoodLazyRoute: typeof MoodLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  JournalLazyRoute: JournalLazyRoute,
  MoodLazyRoute: MoodLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/journal",
        "/mood"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/journal": {
      "filePath": "journal.lazy.tsx"
    },
    "/mood": {
      "filePath": "mood.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
